### PR TITLE
Few More Icons

### PR DESCRIPTION
**Pull request by TheKitBoi**
Add Winning Eleven 2008 Icon
Update Virtual Fighter 5 Esports and Wangan Midnight Maximum Tune 3DX+ Icons

### CODE REVIEW

**Comment by EmiMidnight** [comment]
Hi, sorry, i merged the other request first that already had Winning Eleven. Could you remove the conflicting file so i can merge this?

**Comment by TheKitBoi** [comment]
ok

**Comment by TheKitBoi** [comment]
done

**Comment by EmiMidnight** [comment]
thanks

**Pull request merged**
