### PR TITLE
Massive game icons update

### PR DESCRIPTION
**Pull request by rufotheone-fr**

### CODE REVIEW

**Comment by rufotheone-fr** [comment]
- Dirty Drivin'/Star Wars/Akai Katana Shin/Rumble Fish 2 are from Pooterman
- KOF98/KOFXIIIClimax/Samurai Shodown Sen/Spica are duplicates of already uploaded icons
- The Rest is from myself

**Comment by Nezarn** [comment]
Groove Coaster 2 image is wrong, also why are they 510x510? proper size is 512x512

edit: also pooterman made more icons, add those too

**Comment by rufotheone-fr** [comment]
It's because I've made those which are 510x510.
ArcadeLove.png is 430x430 (and some others) since a long time so I thought it wasn't a problem as long as the logo is square.
I'll see if I can find the new icons made by Pooterman but I've already added some from him.

**Comment by rufotheone-fr** [comment]
There you go.

**Pull request closed without merging**
